## About
This notebook explores the MovieLens dataset, focusing on movies and tags to understand how they can be used in the movie recommendation system.

In [2]:
import pandas as pd

## Movies exploration

In [3]:
movies = pd.read_csv('../Data/ml-latest/movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies.shape

(86537, 3)

In [5]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 86537 entries, 0 to 86536
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  86537 non-null  int64
 1   title    86537 non-null  str
 2   genres   86537 non-null  str
dtypes: int64(1), str(2)
memory usage: 2.0 MB

In [6]:
movies['genres'].head()

0    Adventure|Animation|Children|Comedy|Fantasy
1                     Adventure|Children|Fantasy
2                                 Comedy|Romance
3                           Comedy|Drama|Romance
4                                         Comedy
Name: genres, dtype: str

Converting text to list:

In [7]:
movies['genres'] = movies['genres'].apply(lambda x: x.split('|'))

Gathering all genres to see how many and to understand feature space (i.e., the space where each data point is represented by its features.
(dimensions = features, points = observations)):

In [8]:
all_genres = set(g for genres in movies['genres'] for g in genres)
len(all_genres)

20

In [9]:
all_genres

{'(no genres listed)',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'IMAX',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western'}

### Insights
- Movies may have multiple genres.
- The dataset is multi-label.
- Movies with missing genre ('no genres listed') may be filtered out from the dataset, since they do not provide useful information.
- Good for content-based filtering.

## Tags exploration

In [10]:
tags = pd.read_csv('../Data/ml-latest/tags.csv')
tags.head()

   userId  movieId            tag   timestamp
0      10      260   good vs evil  1430666558
1      10      260  Harrison Ford  1430666505
2      10      260         sci-fi  1430666538
3      14     1221      Al Pacino  1311600756
4      14     1221          mafia  1311600746

In [11]:
tags.shape

(2328315, 4)

Tags has 2328315 instances (), 4 features ().

In [13]:
tags.info()

<class 'pandas.DataFrame'>
RangeIndex: 2328315 entries, 0 to 2328314
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   tag        str
 3   timestamp  int64
dtypes: int64(3), str(1)
memory usage: 71.1 MB

Unique movie Id's:

In [14]:
tags['movieId'].nunique()

53452

Amount of tags per movie:

In [15]:
tags_per_movie = tags.groupby('movieId').size()
tags_per_movie.head()

movieId
1    1440
2     653
3      36
4      13
5      68
dtype: int64

Most movies has few tags, but some has very many:

In [16]:
tags_per_movie.describe()

count    53452.000000
mean        43.558988
std        197.466261
min          1.000000
25%          2.000000
50%          6.000000
75%         18.000000
max      11152.000000
dtype: float64

The most common tags:

In [17]:
tags['tag'].value_counts().head(10)

tag
sci-fi                14319
atmospheric           12172
action                10683
comedy                10161
surreal                9142
funny                  9094
visually appealing     8890
twist ending           8325
thought-provoking      7727
dark comedy            7659
Name: count, dtype: int64

Displaying all tags for one movie to understand how rich the information is:

In [18]:
tags[tags['movieId'] == 260]['tag']

0            good vs evil
1           Harrison Ford
2                  sci-fi
249           influential
250            space epic
                ...
2328052             space
2328142    epic adventure
2328143    old FX quality
2328144         old movie
2328145      space combat
Name: tag, Length: 11152, dtype: str

In [19]:
tags.isnull().sum()

userId        0
movieId       0
tag          17
timestamp     0
dtype: int64

### Insights
- Tags are user-generated features.
- A lot more detailed than genres, which could improve the recommendations.